/**
 * DONNÉES ILLUSTRATIVES ET PÉDAGOGIQUES UNIQUEMENT.
 * Ces hypothèses ne constituent pas une prévision ni une recommandation.
 * Les rendements réels peuvent différer significativement.
 */
import type { AssetAssumption, AssetClassId } from './simulationTypes';

export const ASSET_ASSUMPTIONS: Record<AssetClassId, AssetAssumption> = {
  'fonds-euros': {
    id: 'fonds-euros',
    label: 'Fonds en euros',
    shortLabel: 'Fonds €',
    expectedReturn: 0.025,
    volatility: 0.005,
    ratesSensitivity: -0.3,
    inflationSensitivity: -0.2,
    growthSensitivity: 0.1,
    creditSensitivity: -0.1,
    liquidity: 'haute',
    minHorizon: 1,
    riskLevel: 1,
    fees: 0.008,
    category: 'monetary',
  },
  'monétaire': {
    id: 'monétaire',
    label: 'Fonds monétaires',
    shortLabel: 'Monétaire',
    expectedReturn: 0.033,
    volatility: 0.003,
    ratesSensitivity: 0.8,
    inflationSensitivity: 0.3,
    growthSensitivity: 0.05,
    creditSensitivity: -0.05,
    liquidity: 'haute',
    minHorizon: 0,
    riskLevel: 1,
    fees: 0.003,
    category: 'monetary',
  },
  'obligations-souveraines': {
    id: 'obligations-souveraines',
    label: 'Obligations souveraines',
    shortLabel: 'Oblig. souv.',
    expectedReturn: 0.035,
    volatility: 0.055,
    ratesSensitivity: -0.85,
    inflationSensitivity: -0.4,
    growthSensitivity: 0.1,
    creditSensitivity: -0.1,
    liquidity: 'haute',
    minHorizon: 2,
    riskLevel: 2,
    fees: 0.005,
    category: 'bonds',
  },
  'obligations-entreprises': {
    id: 'obligations-entreprises',
    label: 'Obligations d\'entreprises (IG)',
    shortLabel: 'Oblig. corp.',
    expectedReturn: 0.046,
    volatility: 0.07,
    ratesSensitivity: -0.6,
    inflationSensitivity: -0.2,
    growthSensitivity: 0.3,
    creditSensitivity: -0.5,
    liquidity: 'moyenne',
    minHorizon: 3,
    riskLevel: 3,
    fees: 0.007,
    category: 'bonds',
  },
  'obligations-haut-rendement': {
    id: 'obligations-haut-rendement',
    label: 'Obligations haut rendement',
    shortLabel: 'High Yield',
    expectedReturn: 0.065,
    volatility: 0.12,
    ratesSensitivity: -0.3,
    inflationSensitivity: -0.1,
    growthSensitivity: 0.6,
    creditSensitivity: -0.9,
    liquidity: 'moyenne',
    minHorizon: 4,
    riskLevel: 4,
    fees: 0.01,
    category: 'bonds',
  },
  'actions-france': {
    id: 'actions-france',
    label: 'Actions françaises',
    shortLabel: 'Actions FR',
    expectedReturn: 0.075,
    volatility: 0.17,
    ratesSensitivity: -0.2,
    inflationSensitivity: 0.2,
    growthSensitivity: 0.85,
    creditSensitivity: -0.3,
    liquidity: 'haute',
    minHorizon: 5,
    riskLevel: 6,
    fees: 0.012,
    category: 'equities',
  },
  'actions-europe': {
    id: 'actions-europe',
    label: 'Actions européennes',
    shortLabel: 'Actions EU',
    expectedReturn: 0.077,
    volatility: 0.165,
    ratesSensitivity: -0.2,
    inflationSensitivity: 0.2,
    growthSensitivity: 0.85,
    creditSensitivity: -0.25,
    liquidity: 'haute',
    minHorizon: 5,
    riskLevel: 6,
    fees: 0.01,
    category: 'equities',
  },
  'actions-us': {
    id: 'actions-us',
    label: 'Actions américaines',
    shortLabel: 'Actions US',
    expectedReturn: 0.088,
    volatility: 0.185,
    ratesSensitivity: -0.15,
    inflationSensitivity: 0.15,
    growthSensitivity: 0.9,
    creditSensitivity: -0.2,
    liquidity: 'haute',
    minHorizon: 5,
    riskLevel: 6,
    fees: 0.008,
    category: 'equities',
  },
  'actions-monde': {
    id: 'actions-monde',
    label: 'Actions monde diversifiées',
    shortLabel: 'Actions Monde',
    expectedReturn: 0.082,
    volatility: 0.175,
    ratesSensitivity: -0.15,
    inflationSensitivity: 0.2,
    growthSensitivity: 0.88,
    creditSensitivity: -0.2,
    liquidity: 'haute',
    minHorizon: 5,
    riskLevel: 6,
    fees: 0.009,
    category: 'equities',
  },
  'actions-émergentes': {
    id: 'actions-émergentes',
    label: 'Actions marchés émergents',
    shortLabel: 'Actions EM',
    expectedReturn: 0.095,
    volatility: 0.24,
    ratesSensitivity: -0.1,
    inflationSensitivity: 0.3,
    growthSensitivity: 0.95,
    creditSensitivity: -0.4,
    liquidity: 'moyenne',
    minHorizon: 7,
    riskLevel: 7,
    fees: 0.015,
    category: 'equities',
  },
  'etf-diversifié': {
    id: 'etf-diversifié',
    label: 'ETF diversifié multi-actifs',
    shortLabel: 'ETF Divers.',
    expectedReturn: 0.062,
    volatility: 0.11,
    ratesSensitivity: -0.3,
    inflationSensitivity: 0.15,
    growthSensitivity: 0.65,
    creditSensitivity: -0.2,
    liquidity: 'haute',
    minHorizon: 4,
    riskLevel: 4,
    fees: 0.004,
    category: 'equities',
  },
  'immobilier-coté': {
    id: 'immobilier-coté',
    label: 'Immobilier coté (SIIC/REIT)',
    shortLabel: 'SIIC/REIT',
    expectedReturn: 0.068,
    volatility: 0.19,
    ratesSensitivity: -0.55,
    inflationSensitivity: 0.4,
    growthSensitivity: 0.5,
    creditSensitivity: -0.3,
    liquidity: 'haute',
    minHorizon: 5,
    riskLevel: 5,
    fees: 0.012,
    category: 'real-estate',
  },
  'scpi': {
    id: 'scpi',
    label: 'SCPI (Sociétés Civiles de Placement Immobilier)',
    shortLabel: 'SCPI',
    expectedReturn: 0.052,
    volatility: 0.082,
    ratesSensitivity: -0.4,
    inflationSensitivity: 0.35,
    growthSensitivity: 0.4,
    creditSensitivity: -0.2,
    liquidity: 'faible',
    minHorizon: 8,
    riskLevel: 3,
    fees: 0.014,
    category: 'real-estate',
  },
  'private-equity': {
    id: 'private-equity',
    label: 'Private equity',
    shortLabel: 'Private Eq.',
    expectedReturn: 0.11,
    volatility: 0.28,
    ratesSensitivity: -0.1,
    inflationSensitivity: 0.2,
    growthSensitivity: 1.0,
    creditSensitivity: -0.35,
    liquidity: 'très faible',
    minHorizon: 10,
    riskLevel: 7,
    fees: 0.025,
    category: 'alternatives',
  },
  'produits-structurés': {
    id: 'produits-structurés',
    label: 'Produits structurés',
    shortLabel: 'Structurés',
    expectedReturn: 0.055,
    volatility: 0.09,
    ratesSensitivity: -0.3,
    inflationSensitivity: 0.05,
    growthSensitivity: 0.5,
    creditSensitivity: -0.4,
    liquidity: 'faible',
    minHorizon: 5,
    riskLevel: 4,
    fees: 0.018,
    category: 'structured',
  },
  'liquidités': {
    id: 'liquidités',
    label: 'Liquidités et dépôts',
    shortLabel: 'Liquidités',
    expectedReturn: 0.018,
    volatility: 0.001,
    ratesSensitivity: 0.5,
    inflationSensitivity: -0.5,
    growthSensitivity: 0.0,
    creditSensitivity: 0.0,
    liquidity: 'haute',
    minHorizon: 0,
    riskLevel: 1,
    fees: 0.0,
    category: 'monetary',
  },
};
