/**
 * DONNÉES ILLUSTRATIVES ET PÉDAGOGIQUES UNIQUEMENT.
 * Les allocations présentées sont des exemples indicatifs.
 */
import type { RiskProfile, RiskProfileDefinition } from './simulationTypes';

export const RISK_PROFILES: Record<RiskProfile, RiskProfileDefinition> = {
  'prudent': {
    id: 'prudent',
    label: 'Prudent',
    description: 'Priorité à la préservation du capital et à la stabilité. Faible exposition aux actifs risqués, horizon court à moyen terme.',
    allocation: {
      'fonds-euros': 0.30,
      'monétaire': 0.10,
      'obligations-souveraines': 0.25,
      'obligations-entreprises': 0.15,
      'etf-diversifié': 0.08,
      'scpi': 0.07,
      'liquidités': 0.05,
    },
    expectedReturn: 0.032,
    volatility: 0.045,
    minHorizon: 3,
    maxDrawdown: -0.08,
    liquidityRatio: 0.45,
    color: 'hsl(218 28% 55%)',
  },
  'équilibré': {
    id: 'équilibré',
    label: 'Équilibré',
    description: 'Recherche d\'un équilibre entre rendement et sécurité. Mix actions / obligations, horizon moyen à long terme.',
    allocation: {
      'fonds-euros': 0.20,
      'obligations-souveraines': 0.10,
      'obligations-entreprises': 0.15,
      'actions-monde': 0.25,
      'etf-diversifié': 0.15,
      'scpi': 0.10,
      'liquidités': 0.05,
    },
    expectedReturn: 0.055,
    volatility: 0.09,
    minHorizon: 6,
    maxDrawdown: -0.18,
    liquidityRatio: 0.25,
    color: 'hsl(222 50% 11%)',
  },
  'dynamique': {
    id: 'dynamique',
    label: 'Dynamique',
    description: 'Acceptation d\'une volatilité élevée en contrepartie d\'un potentiel de rendement plus important. Horizon long terme.',
    allocation: {
      'fonds-euros': 0.05,
      'obligations-haut-rendement': 0.10,
      'actions-france': 0.10,
      'actions-europe': 0.10,
      'actions-us': 0.15,
      'actions-monde': 0.20,
      'actions-émergentes': 0.10,
      'etf-diversifié': 0.10,
      'private-equity': 0.05,
      'scpi': 0.05,
    },
    expectedReturn: 0.082,
    volatility: 0.155,
    minHorizon: 10,
    maxDrawdown: -0.35,
    liquidityRatio: 0.05,
    color: 'hsl(218 45% 38%)',
  },
  'personnalisé': {
    id: 'personnalisé',
    label: 'Personnalisé',
    description: 'Allocation sur-mesure définie avec votre conseiller KANTI, adaptée à vos contraintes spécifiques.',
    allocation: {
      'fonds-euros': 0.15,
      'obligations-entreprises': 0.10,
      'actions-monde': 0.30,
      'etf-diversifié': 0.20,
      'scpi': 0.15,
      'private-equity': 0.05,
      'liquidités': 0.05,
    },
    expectedReturn: 0.065,
    volatility: 0.11,
    minHorizon: 8,
    maxDrawdown: -0.22,
    liquidityRatio: 0.20,
    color: 'hsl(224 60% 7%)',
  },
};
